In [39]:
import ROOT
import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt

# === Configuration ===
year = "2016APV"
bgr = "signal"
folder = f"plots/{bgr}/{year}/root"

# === Dictionary to hold all data in memory ===
tables = {}

# === List ROOT files ===
root_files = [f for f in os.listdir(folder) if f.endswith('.root')]
print(f"Processing {len(root_files)} ROOT files...")

for filename in root_files:
    print(f"\nProcessing: {filename}")
    file_path = f"{folder}/{filename}"

    try:
        file = ROOT.TFile.Open(file_path)
        if not file or file.IsZombie():
            print(f"  ✗ Skipping invalid file: {filename}")
            continue

        # --- Collect histograms ---
        histograms = []
        for key in file.GetListOfKeys():
            obj = key.ReadObj()
            if obj and obj.InheritsFrom("TH1"):
                histograms.append(obj)

        if not histograms:
            file.Close()
            print(f"  ⚠️ No histograms found in {filename}")
            continue

        # --- Build a table (DataFrame) with binning information ---
        first_hist = histograms[0]
        nbins = first_hist.GetNbinsX()
        bin_data = {
            "bin_number": np.arange(1, nbins + 1),
            "low_edge": [first_hist.GetBinLowEdge(i) for i in range(1, nbins + 1)],
            "center": [first_hist.GetBinCenter(i) for i in range(1, nbins + 1)],
            "high_edge": [first_hist.GetBinLowEdge(i) + first_hist.GetBinWidth(i) for i in range(1, nbins + 1)],
            "width": [first_hist.GetBinWidth(i) for i in range(1, nbins + 1)],
        }

        # Add each histogram as a column
        for hist in histograms:
            contents = [hist.GetBinContent(i) for i in range(1, nbins + 1)]
            bin_data[hist.GetName()] = contents

        df = pd.DataFrame(bin_data)

        # Store the DataFrame in the dictionary
        tables[filename] = df

        print(f"  ✓ Loaded {len(histograms)} histograms with {nbins} bins")

        file.Close()

    except Exception as e:
        print(f"  ✗ Error processing {filename}: {str(e)}")

print("\n✅ All ROOT files loaded in memory.")
print("You can access them with:")
print("  tables['<filename>.root']")

# === Optional: helper function to visualize a histogram ===
def show_histogram(file_name, hist_name):
    """
    Plot a histogram from the in-memory table.

    Args:
        file_name (str): ROOT filename key in `tables`.
        hist_name (str): Column name of the histogram to plot.
    """
    if file_name not in tables:
        print(f"⚠️ File '{file_name}' not found in tables.")
        return
    df = tables[file_name]

    if hist_name not in df.columns:
        print(f"⚠️ Histogram '{hist_name}' not found in {file_name}.")
        print("Available histograms:", [c for c in df.columns if c not in ['bin_number','low_edge','center','high_edge','width']])
        return

    plt.figure(figsize=(8, 5))
    plt.bar(df["center"], df[hist_name], width=df["width"], align="center", alpha=0.7)
    plt.xlabel("X-axis (variable)")
    plt.ylabel("Entries")
    plt.title(f"{hist_name} — {file_name}")
    plt.grid(True, alpha=0.3)
    plt.show()

Processing 17 ROOT files...

Processing: DYJetsToLNu_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: Diboson_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: Higgs_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: QCD_signal_tau_2016APV.root
  ✓ Loaded 73 histograms with 9 bins

Processing: SignalTau_1000GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_1500GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_2000GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_3000GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_300GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_400GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_600GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SignalTau_750GeV_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: SingleTop_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: Total_bgr_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: WJetToLNu_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

Processing: data_obs_signal_tau_2016APV.root
  ✓ Loaded 1 histograms with 9 bins

Processing: tt_signal_tau_2016APV.root
  ✓ Loaded 59 histograms with 9 bins

✅ All ROOT files loaded in memory.
You can access them with:
  tables['<filename>.root']

In [40]:
from IPython.display import display  # For pretty DataFrame display in notebooks

for root_name in list(tables.keys()):
    df = tables[root_name]
    
    print("==================================================================")
    print(f"📁 ROOT file: {root_name}")
    
    # --- List all available histograms in the file ---
    all_hists = [c for c in df.columns 
                 if c not in ['bin_number', 'low_edge', 'center', 'high_edge', 'width']]
    
    print("📜 Available histograms:")
    for h in all_hists:
        print(f"   • {h}")
    
    # --- Find the histogram that ends with 'nom' ---
    hist_candidates = [c for c in all_hists if c.endswith("nom")]
    
    if not hist_candidates:
        print(f"⚠️ No histogram ending with 'nom' found in {root_name}.\n")
        continue
    
    # Use the first histogram found that matches the 'nom' pattern
    hist_name = hist_candidates[0]
    
    # --- Extract histogram info ---
    nbins = len(df)
    xmin = df["low_edge"].min()
    xmax = df["high_edge"].max()
    
    print(f"\n📊 Selected histogram (ends with 'nom'): {hist_name}")
    print(f"   • Number of bins: {nbins}")
    print(f"   • Range: [{xmin:.2f}, {xmax:.2f}]\n")
    
    # --- Add a total row at the bottom ---
    total_value = df[hist_name].sum()
    total_row = {
        "low_edge": "Total",
        "high_edge": "",
        hist_name: total_value
    }
    df_with_total = pd.concat([df[["low_edge", "high_edge", hist_name]], pd.DataFrame([total_row])], ignore_index=True)
    
    # --- Display the histogram data as a pandas table with total row ---
    display(df_with_total)

==================================================================
📁 ROOT file: DYJetsToLNu_signal_tau_2016APV.root
📜 Available histograms:
   • DYJetsToLNu_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): DYJetsToLNu_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  DYJetsToLNu_signal_tau_2016APV_nom
0      0.0      20.0                           23.013720
1     20.0      40.0                           17.234488
2     40.0      60.0                            7.383359
3     60.0      80.0                           -1.529812
4     80.0     100.0                            0.000000
5    100.0     120.0                           -1.595932
6    120.0     150.0                            0.000000
7    150.0     200.0                            0.000000
8    200.0     300.0                            0.000000
9    Total                                     44.505822

==================================================================
📁 ROOT file: Diboson_signal_tau_2016APV.root
📜 Available histograms:
   • Diboson_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): Diboson_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  Diboson_signal_tau_2016APV_nom
0      0.0      20.0                        4.028414
1     20.0      40.0                        4.270422
2     40.0      60.0                        2.558676
3     60.0      80.0                        1.028183
4     80.0     100.0                        0.578063
5    100.0     120.0                        0.310534
6    120.0     150.0                        0.367172
7    150.0     200.0                        0.364748
8    200.0     300.0                        0.280712
9    Total                                 13.786924

==================================================================
📁 ROOT file: Higgs_signal_tau_2016APV.root
📜 Available histograms:
   • Higgs_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): Higgs_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  Higgs_signal_tau_2016APV_nom
0      0.0      20.0                      0.317253
1     20.0      40.0                      0.367100
2     40.0      60.0                      0.396356
3     60.0      80.0                      0.105858
4     80.0     100.0                      0.052155
5    100.0     120.0                      0.076638
6    120.0     150.0                      0.000000
7    150.0     200.0                      0.000000
8    200.0     300.0                      0.000000
9    Total                                1.315359

==================================================================
📁 ROOT file: QCD_signal_tau_2016APV.root
📜 Available histograms:
   • QCD_signal_tau_2016APV_nom
   • CMS_pileup_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): QCD_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  QCD_signal_tau_2016APV_nom
0      0.0      20.0                  365.802216
1     20.0      40.0                  140.736862
2     40.0      60.0                  175.900986
3     60.0      80.0                   84.809090
4     80.0     100.0                   37.944176
5    100.0     120.0                   25.728212
6    120.0     150.0                   69.012741
7    150.0     200.0                   17.189709
8    200.0     300.0                   93.073616
9    Total                           1010.197607

==================================================================
📁 ROOT file: SignalTau_1000GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_1000GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_1000GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_1000GeV_signal_tau_2016APV_nom
0      0.0      20.0                                  6.540933
1     20.0      40.0                                  8.042727
2     40.0      60.0                                  5.948857
3     60.0      80.0                                  7.885641
4     80.0     100.0                                  6.461908
5    100.0     120.0                                  8.260502
6    120.0     150.0                                 19.768055
7    150.0     200.0                                 35.397575
8    200.0     300.0                               1187.716187
9    Total                                         1286.022385

==================================================================
📁 ROOT file: SignalTau_1500GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_1500GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_1500GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_1500GeV_signal_tau_2016APV_nom
0      0.0      20.0                                  0.498008
1     20.0      40.0                                  0.770349
2     40.0      60.0                                  0.896365
3     60.0      80.0                                  0.640603
4     80.0     100.0                                  0.984342
5    100.0     120.0                                  1.011518
6    120.0     150.0                                  1.791164
7    150.0     200.0                                  3.945033
8    200.0     300.0                                174.787003
9    Total                                          185.324385

==================================================================
📁 ROOT file: SignalTau_2000GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_2000GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_2000GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_2000GeV_signal_tau_2016APV_nom
0      0.0      20.0                                  0.088528
1     20.0      40.0                                  0.140414
2     40.0      60.0                                  0.116212
3     60.0      80.0                                  0.107850
4     80.0     100.0                                  0.074098
5    100.0     120.0                                  0.147951
6    120.0     150.0                                  0.403928
7    150.0     200.0                                  0.628774
8    200.0     300.0                                 32.547421
9    Total                                           34.255176

==================================================================
📁 ROOT file: SignalTau_3000GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_3000GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_3000GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_3000GeV_signal_tau_2016APV_nom
0      0.0      20.0                                  0.009213
1     20.0      40.0                                  0.009006
2     40.0      60.0                                  0.005733
3     60.0      80.0                                  0.007541
4     80.0     100.0                                  0.012360
5    100.0     120.0                                  0.012640
6    120.0     150.0                                  0.021645
7    150.0     200.0                                  0.042901
8    200.0     300.0                                  1.797149
9    Total                                            1.918188

==================================================================
📁 ROOT file: SignalTau_300GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_300GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_300GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_300GeV_signal_tau_2016APV_nom
0      0.0      20.0                               757.375000
1     20.0      40.0                               347.816162
2     40.0      60.0                               184.101074
3     60.0      80.0                               545.202271
4     80.0     100.0                               922.192993
5    100.0     120.0                              1288.020020
6    120.0     150.0                              2553.995605
7    150.0     200.0                              5099.158203
8    200.0     300.0                             12829.217773
9    Total                                       24527.079102

==================================================================
📁 ROOT file: SignalTau_400GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_400GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_400GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_400GeV_signal_tau_2016APV_nom
0      0.0      20.0                               256.675385
1     20.0      40.0                               231.367676
2     40.0      60.0                               239.075714
3     60.0      80.0                               271.252136
4     80.0     100.0                               222.895569
5    100.0     120.0                               513.650513
6    120.0     150.0                               857.080322
7    150.0     200.0                              1896.121826
8    200.0     300.0                             12388.664062
9    Total                                       16876.783203

==================================================================
📁 ROOT file: SignalTau_600GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_600GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_600GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_600GeV_signal_tau_2016APV_nom
0      0.0      20.0                                21.681412
1     20.0      40.0                                29.937443
2     40.0      60.0                                47.730251
3     60.0      80.0                                42.601913
4     80.0     100.0                                86.558929
5    100.0     120.0                                64.620880
6    120.0     150.0                               138.066711
7    150.0     200.0                               432.903046
8    200.0     300.0                              6587.540039
9    Total                                        7451.640625

==================================================================
📁 ROOT file: SignalTau_750GeV_signal_tau_2016APV.root
📜 Available histograms:
   • SignalTau_750GeV_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SignalTau_750GeV_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SignalTau_750GeV_signal_tau_2016APV_nom
0      0.0      20.0                                29.769381
1     20.0      40.0                                17.324392
2     40.0      60.0                                19.479729
3     60.0      80.0                                26.327545
4     80.0     100.0                                32.049309
5    100.0     120.0                                35.136055
6    120.0     150.0                                46.512802
7    150.0     200.0                               155.459564
8    200.0     300.0                              3355.187012
9    Total                                        3717.245789

==================================================================
📁 ROOT file: SingleTop_signal_tau_2016APV.root
📜 Available histograms:
   • SingleTop_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): SingleTop_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  SingleTop_signal_tau_2016APV_nom
0      0.0      20.0                        139.722900
1     20.0      40.0                        124.566780
2     40.0      60.0                         93.325974
3     60.0      80.0                         47.614349
4     80.0     100.0                         19.833721
5    100.0     120.0                          6.492648
6    120.0     150.0                          9.955634
7    150.0     200.0                          9.457542
8    200.0     300.0                         17.706985
9    Total                                  468.676535

==================================================================
📁 ROOT file: Total_bgr_signal_tau_2016APV.root
📜 Available histograms:
   • Total_bgr_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): Total_bgr_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  Total_bgr_signal_tau_2016APV_nom
0      0.0      20.0                       2038.114380
1     20.0      40.0                       1540.609985
2     40.0      60.0                       1142.302246
3     60.0      80.0                       1256.041870
4     80.0     100.0                       1412.304932
5    100.0     120.0                       1975.138794
6    120.0     150.0                       3709.420898
7    150.0     200.0                       7734.998535
8    200.0     300.0                      36726.453125
9    Total                                57535.384766

==================================================================
📁 ROOT file: WJetToLNu_signal_tau_2016APV.root
📜 Available histograms:
   • WJetToLNu_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): WJetToLNu_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  WJetToLNu_signal_tau_2016APV_nom
0      0.0      20.0                        249.620987
1     20.0      40.0                        212.613861
2     40.0      60.0                        137.714233
3     60.0      80.0                         80.279343
4     80.0     100.0                         20.226593
5    100.0     120.0                          6.224182
6    120.0     150.0                          4.968804
7    150.0     200.0                          2.502737
8    200.0     300.0                         13.899734
9    Total                                  728.050475

==================================================================
📁 ROOT file: data_obs_signal_tau_2016APV.root
📜 Available histograms:
   • data_obs_signal_tau_2016APV_nom

📊 Selected histogram (ends with 'nom'): data_obs_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  data_obs_signal_tau_2016APV_nom
0      0.0      20.0                              0.0
1     20.0      40.0                              0.0
2     40.0      60.0                              0.0
3     60.0      80.0                              0.0
4     80.0     100.0                              0.0
5    100.0     120.0                              0.0
6    120.0     150.0                              0.0
7    150.0     200.0                              0.0
8    200.0     300.0                              0.0
9    Total                                        0.0

==================================================================
📁 ROOT file: tt_signal_tau_2016APV.root
📜 Available histograms:
   • tt_signal_tau_2016APV_nom
   • CMS_rochester_signal_tau_2016APV_Up
   • CMS_t_energy_signal_tau_2016APV_Up
   • CMS_scale_j_signal_tau_2016APV_Up
   • CMS_res_j_signal_tau_2016APV_Up
   • CMS_MET_unclustered_signal_tau_2016APV_Up
   • CMS_scale_fj_signal_tau_2016APV_Up
   • CMS_res_fj_signal_tau_2016APV_Up
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Up
   • ps_ISR_signal_tau_2016APV_Up
   • ps_FSR_signal_tau_2016APV_Up
   • PDF_signal_tau_2016APV_Up
   • Alpha(PDF)_signal_tau_2016APV_Up
   • CMS_pileup_signal_tau_2016APV_Up
   • CMS_eff_j_PUJET_signal_tau_2016APV_Up
   • CMS_btag_heavy_signal_tau_2016APV_Up
   • CMS_btag_light_signal_tau_2016APV_Up
   • CMS_eff_e_id_signal_tau_2016APV_Up
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Up
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Up
   • CMS_eff_m_reco_signal_tau_2016APV_Up
   • CMS_eff_m_id_signal_tau_2016APV_Up
   • CMS_eff_m_iso_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Up
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Up
   • CMS_eff_T_particleNet_signal_tau_2016APV_Up
   • CMS_eff_W_particleNet_signal_tau_2016APV_Up
   • CMS_eff_MET_trigger_signal_tau_2016APV_Up
   • CMS_rochester_signal_tau_2016APV_Down
   • CMS_t_energy_signal_tau_2016APV_Down
   • CMS_scale_j_signal_tau_2016APV_Down
   • CMS_res_j_signal_tau_2016APV_Down
   • CMS_MET_unclustered_signal_tau_2016APV_Down
   • CMS_scale_fj_signal_tau_2016APV_Down
   • CMS_res_fj_signal_tau_2016APV_Down
   • CMS_l1_ecal_prefiring_signal_tau_2016APV_Down
   • ps_ISR_signal_tau_2016APV_Down
   • ps_FSR_signal_tau_2016APV_Down
   • PDF_signal_tau_2016APV_Down
   • Alpha(PDF)_signal_tau_2016APV_Down
   • CMS_pileup_signal_tau_2016APV_Down
   • CMS_eff_j_PUJET_signal_tau_2016APV_Down
   • CMS_btag_heavy_signal_tau_2016APV_Down
   • CMS_btag_light_signal_tau_2016APV_Down
   • CMS_eff_e_id_signal_tau_2016APV_Down
   • CMS_eff_e_reco_above20_signal_tau_2016APV_Down
   • CMS_eff_e_reco_below20_signal_tau_2016APV_Down
   • CMS_eff_m_reco_signal_tau_2016APV_Down
   • CMS_eff_m_id_signal_tau_2016APV_Down
   • CMS_eff_m_iso_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSe_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSmu_signal_tau_2016APV_Down
   • CMS_eff_tau_idDeepTauVSjet_signal_tau_2016APV_Down
   • CMS_eff_T_particleNet_signal_tau_2016APV_Down
   • CMS_eff_W_particleNet_signal_tau_2016APV_Down
   • CMS_eff_MET_trigger_signal_tau_2016APV_Down

📊 Selected histogram (ends with 'nom'): tt_signal_tau_2016APV_nom
   • Number of bins: 9
   • Range: [0.00, 300.00]

  low_edge high_edge  tt_signal_tau_2016APV_nom
0      0.0      20.0                 548.773254
1     20.0      40.0                 546.149170
2     40.0      60.0                 403.569702
3     60.0      80.0                 234.518433
4     80.0     100.0                 100.384834
5    100.0     120.0                  52.770599
6    120.0     150.0                  76.488953
7    150.0     200.0                  99.016800
8    200.0     300.0                 137.110062
9    Total                          2198.781807